routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/login', 'App\Http\Controllers\LoginController@login')->name('login');
Route::post('/login', 'App\Http\Controllers\LoginController@authenticate')->name('authenticate');
Route::get('/logout', 'App\Http\Controllers\LoginController@logout')->name('logout');


Route::get('/', function () {
    return view('welcome');
});

Route::group([''], function() { // GROUP 1
    Route::get('/login', 'LoginController@login')->name('login');
    Route::post('/login', 'LoginController@authenticate')->name('authenticate');

    Route::get('/tickets/search', 'TicketController@search')->name('tickets.search');
    Route::get('/tickets/create', 'TicketController@create')->name('tickets.create');
    Route::post('/tickets', 'TicketController@store')->name('tickets.store');
    Route::get('/tickets/{ticket}', 'TicketController@show')->name('tickets.show');

    Route::resource('/comments', 'CommentController')->only('store', 'update', 'destroy');

    Route::middleware(['auth'])->group(function() { // GROUP 2
        Route::get('/tickets', 'TicketController@index')->name('tickets.index');
        Route::get('/logout', 'LoginController@logout')->name('logout');
    });
});

//Route::get('/tickets/search', 'TicketController@search')->name('tickets.search');

//Route::resource('tickets', 'TicketController');

app/Models/Ticket.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Ticket extends Model
{
    use HasFactory;

    protected $fillable = [
        'customer_name',
        'email',
        'phone',
        'description',
        'ref',
        'status',
    ];

    protected $with = ['comments', 'comments.user'];

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function getLastCommentedAgentAttribute()
    {
        return $this->comments->sortByDesc('created_at')
            ->whereNotNull('user')->pluck('user')->first();
    }
}

app/Http/Controllers/API/V1/TicketsController.php
<?php

namespace App\Http\Controllers\API\V1;

use App\Http\Controllers\Controller;
use App\Models\Ticket;
use App\Events\TicketCreated;
use Mail;
use Illuminate\Http\Request;

class TicketsController extends Controller
{
    public function store(Request $request){   
        $this->validate($request, [
            'customer_name' => 'required|max:200',
            'email' => 'required|email',
            'description' => 'required',
        ]);

        $data = $request->only([
            'customer_name',
            'email',
            'phone',
            'description',
        ]);

        $data['ref'] = sha1(time());
        $data['status'] = 0;

        $ticket = Ticket::create($data);

        if($ticket){
            TicketCreated::dispatch($ticket);

            return response()->json([
                'data' => $ticket,
                'message' => 'Your ticket is created successfully. Please write down the reference number to check the ticket status later.'
            ]);

            return response()->json([
                'data' => null,
                'message' => 'Oops! Could not create your ticket. Please try later.'
            ], 500);
        }
    }

    public function view(){
        return Ticket::all();
    }

    public function search($ref){
        $result = Ticket::where('ref', '=', $ref)->get();
        if(count($result)){
            return response()->json($result);
        }
        else{
            return response()->json(['Result' => 'No Record found'], 404);
        }
        
    }
}

app/Http/Controllers/TicketController.php
<?php

namespace App\Http\Controllers;

use App\Models\Ticket;
use App\Events\TicketCreated;
use Illuminate\Http\Request;
use Mail;

class TicketController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $ticketsQuery = Ticket::query();

        $q = $request->query('q');
        $sortColumn = $request->query('sort', 'created_at');
        $sortDir = $request->query('sort_dir') == 'asc' ? 'asc' : 'desc';
        $sortableColumns = [
            'customer_name',
            'created_at',
            'updated_at',
            'status',
        ];

        // Searching
        if ($q) {
            $ticketsQuery->where('ref', 'LIKE', "%$q%")
                ->orWhere('customer_name', 'LIKE', "%$q%")
                ->orWhere('phone', 'LIKE', "%$q%")
                ->orWhere('description', 'LIKE', "%$q%");
        }

        // Sorting
        if (in_array($sortColumn, $sortableColumns)) {
            $ticketsQuery->orderBy($sortColumn, $sortDir);
        }


        $tickets = $ticketsQuery->paginate($request->query('per_page', 10));

        return view('tickets.index', [
            'tickets' => $tickets,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tickets.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'customer_name' => 'required|max:200',
            'email' => 'required|email',
            'description' => 'required',
        ]);

        $ticket = new Ticket();

        $ticket->customer_name = $request->input('customer_name');
        $ticket->email = $request->input('email');
        $ticket->phone = $request->input('phone');
        $ticket->description = $request->input('description');
        $ticket->ref = sha1(time());
        $ticket->status = 0;

        if ($ticket->save()) {
            TicketCreated::dispatch($ticket);

            return redirect(route('tickets.show', $ticket->id))
                ->with('success', 'Your ticket was successfully created. Please write down the reference number to check the ticket status later. ');
        }

        return redirect()->back()->with('error', 'Oops! Could not create your ticket. Please try later.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function show(Ticket $ticket)
    {
        return view('tickets.show', [
            'ticket' => $ticket,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function edit(Ticket $ticket)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Ticket $ticket)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function destroy(Ticket $ticket)
    {
        //
    }

    public function search(Request $request)
    {
        $ticket = Ticket::where('ref', $request->query('reference'))->first();

        if ($ticket) {
            return redirect(route('tickets.show', $ticket->id));
        }

        return redirect()->back()
            ->with('error', 'Sorry! We could not find the ticket you are looking for. Please check the reference number.');
    }
}

resources/views/tickets/create.blade.php
@extends('layouts.app')

@section('content')

        <div class="text-center mt-5">
            <h1>Open New Ticket</h1>
            <div class="m-5">

                <!-- FORM START -->
                <form class="" action="{{ route('tickets.store') }}" method="post">
                    {{ csrf_field() }}
                    <div class="row justify-content-center">
                        <div class="col-lg-6">

                            <div class="form-group row">
                                <div class="col-md-4 text-md-right">
                                    <label for="customer_name">Your Name</label>
                                </div>
                                <div class="col-md-8">
                                    <input type="text" name="customer_name" value="" class="form-control {{ $errors->has('customer_name') ? 'is-invalid' : '' }}">
                                    @if($errors->has('customer_name'))
                                    <div class="invalid-feedback text-left">
                                        {{ $errors->first('customer_name') }}
                                    </div>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-md-4 text-md-right">
                                    <label for="email">Email</label>
                                </div>
                                <div class="col-md-8">
                                    <input type="text" name="email" value="" class="form-control {{ $errors->has('email') ? 'is-invalid' : '' }}">
                                    @if($errors->has('email'))
                                    <div class="invalid-feedback text-left">
                                        {{ $errors->first('email') }}
                                    </div>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-md-4 text-md-right">
                                    <label for="phone">Phone</label>
                                </div>
                                <div class="col-md-8">
                                    <input type="text" name="phone" value="" class="form-control">
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-md-4 text-md-right">
                                    <label for="description">Description</label>
                                </div>
                                <div class="col-md-8">
                                    <textarea name="description" class="form-control {{ $errors->has('description') ? 'is-invalid' : '' }}"></textarea>
                                    @if($errors->has('description'))
                                    <div class="invalid-feedback text-left">
                                        {{ $errors->first('description') }}
                                    </div>
                                    @endif
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-8 offset-md-4 text-md-right">
                                    <input type="submit" value="Submit" class="btn btn-success">
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
                <!-- FORM END -->

            </div>
        </div>
    
@endsection

resources/views/tickets/index.blade.php
@extends('layouts.app')

@section('content')
<div class="text-center mt-5">
    <h1>All Tickets</h1>
    <div class="m-5">
        <div class="my-4">
            <form class="" action="" method="get">
                <div class="row">
                    <div class="col-3">
                        <select class="form-control" name="sort">
                            <option value="customer_name" {{ request('sort', 'customer_name') == 'customer_name' ? 'selected' : null }}>Customer Name</option>
                            <option value="created_at" {{ request('sort', 'created_at') == 'created_at' ? 'selected' : null }}>Opened Time</option>
                            <option value="updated_at" {{ request('sort', 'updated_at') == 'updated_at' ? 'selected' : null }}>Last Updated Time</option>
                            <option value="status" {{ request('sort', 'status') == 'status' ? 'selected' : null }}>Status</option>
                        </select>
                    </div>
                    <div class="col-3">
                        <select class="form-control" name="sort_dir">
                            <option value="asc" {{ request('sort_dir', 'asc') == 'asc' ? 'selected' : null }}>Ascending</option>
                            <option value="desc" {{ request('sort_dir', 'desc') == 'desc' ? 'selected' : null }}>Descending</option>
                        </select>
                    </div>
                    <div class="col-4">
                        <input type="text" name="q" value="{{ request('q') }}" class="form-control" placeholder="Reference, customer name or phone number">
                    </div>
                    <div class="col-2">
                        <button type="submit" class="btn btn-primary w-100">Search</button>
                    </div>
                </div>
            </form>
        </div>
        @if($tickets->isNotEmpty())
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Customer</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Opened Time</th>
                    <th>Handled By</th>
                    <th>Status</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach($tickets as $ticket)
                <tr>
                    <td>
                        <a href="{{ route('tickets.show', $ticket->id) }}">{{ $ticket->customer_name }}</a>
                    </td>
                    <td>{{ $ticket->email }}</td>
                    <td>{{ $ticket->phone }}</td>
                    <td>{{ $ticket->created_at->format('d/M/Y H:i:s') }}</td>
                    <td>{{ $ticket->lastCommentedAgent ? $ticket->lastCommentedAgent->name : 'None' }}</td>
                    <td></td>
                    <td></td>
                </tr>
                @endforeach
            </tbody>
        </table>
        <div class="mt-4">
            {!! $tickets->links() !!}
        </div>
        @else
        <div class="alert alert-info">
            No tickets are there yet.
        </div>
        @endif
    </div>
</div>
@endsection

resources/views/tickets/show.blade.php
@extends('layouts.app')

@section('content')


<div class="text-center mt-5">
    <h1>Support Ticket</h1>
    <div class="m-5">

        <div class="row justify-content-center">
            <div class="col-lg-6 text-left">

                <table class="table table-bordered table-striped">
                    <tbody>
                        <tr>
                            <th>Ticket Refererence</th>
                            <td>{{ $ticket->ref }}</td>
                        </tr>
                        <tr>
                            <th>Customer Name</th>
                            <td>{{ $ticket->customer_name }}</td>
                        </tr>
                        <tr>
                            <th>Email</th>
                            <td>{{ $ticket->email }}</td>
                        </tr>
                        <tr>
                            <th>Phone</th>
                            <td>{{ $ticket->phone }}</td>
                        </tr>
                        <tr>
                            <th>Description</th>
                            <td>{{ $ticket->description }}</td>
                        </tr>
                    </tbody>
                </table>
                
                @if($ticket->comments->isNotEmpty())
                <div class="comments" id="comments">
                    @foreach($ticket->comments as $comment)
                    <div class="comment mt-5">
                        <div class="comment-author text-muted small">
                            <strong>
                            @if (isset($comment->user->name))
                                {{ $comment->user->name }}
                            @else
                                {{ $ticket->customer_name }}
                            @endif
                            </strong>
                            at
                            {{ $comment->created_at->format('d M Y h:i a') }}
                        </div>
                        <div class="comment-content">
                            {{ $comment->content }}
                        </div>
                    </div>
                    @endforeach
                </div>
                @endif
                <hr>
                <div class="comments-container mt-3">
                    <div class="comments"></div>
                    <div class="comment-editor">
                        <form id="comment-form" class="" action="{{ route('comments.store') }}" method="post">
                            @csrf
                            <input type="hidden" name="ticket_id" value="{{ $ticket->id }}">
                            <div class="form-group">
                                <label for="content">Reply to this ticket:</label>
                                <textarea name="content" rows="3" class="form-control" placeholder="Enter your message here"></textarea>
                            </div>
                            <div class="form-group text-right">
                                <button type="submit" name="button" class="btn btn-success">
                                    <i class="fa fa-spinner fa-spin d-none"></i>
                                    Add Reply
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            
        </div>
        <a class="btn btn-info mt-4" href="/">Go Back</a>
    </div>
</div>

@section('script')
<script type="text/javascript">
    jQuery(document).ready(function($) {
        $('#comment-form').on('submit', function(evt) {
            evt.preventDefault();
            $form = $(this);
            $form.find('button i.fa').removeClass('d-none');
            $.ajax({
                url: $form.attr('action'),
                type: 'POST',
                data: $form.serialize(),
                success: function(data) {
                    let commentsHTML = $('<div>').append(data).find('#comments').html();
                    $('#comments').html(commentsHTML);
                    $form.find('[name="content"]').val('');
                },
                error: function(jqXHR) {
                    let data = JSON.parse(jqXHR.responseText);
                    if (data.message) {
                        alert(data.message);
                    } else {
                        alert('Oops! Something went wrong.');
                    }
                },
                complete: function() {
                    $form.find('button i.fa').addClass('d-none');
                }
            });
        })
    });
</script>
@endsection

@endsection